{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bbn.landsar",
    "module": "motion-model-sdk",
    "version": "0.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "nggjldofu5cvhpfx3jfujp4hoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bbn.roger",
          "module": "roger-plugin-interfaces",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "com.metsci.glimpse",
          "module": "glimpse-util",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "motion-model-sdk-0.0.6-SNAPSHOT.jar",
          "url": "motion-model-sdk-0.0.6-SNAPSHOT.jar",
          "size": 170559,
          "sha512": "3cff91cd82670a9903af25b0d4f5bbf654c8a7b0ea95c5d0a62345e24b42fba34633070e163fbb0e3883b3213a06c549b6c47178c2c3b506a7a252c48c81b838",
          "sha256": "9a7be7b4e8d49b4d1f57e951fa833e5c9d3f58ebd618c092e77e40418a719025",
          "sha1": "6a7826d11f9187837e209bb0d47c3e1a7f0f72fa",
          "md5": "a962c85af198e5c1f8cf53e3d7cf27f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bbn.roger",
          "module": "roger-plugin-interfaces",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "com.metsci.glimpse",
          "module": "glimpse-util",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "motion-model-sdk-0.0.6-SNAPSHOT.jar",
          "url": "motion-model-sdk-0.0.6-SNAPSHOT.jar",
          "size": 170559,
          "sha512": "3cff91cd82670a9903af25b0d4f5bbf654c8a7b0ea95c5d0a62345e24b42fba34633070e163fbb0e3883b3213a06c549b6c47178c2c3b506a7a252c48c81b838",
          "sha256": "9a7be7b4e8d49b4d1f57e951fa833e5c9d3f58ebd618c092e77e40418a719025",
          "sha1": "6a7826d11f9187837e209bb0d47c3e1a7f0f72fa",
          "md5": "a962c85af198e5c1f8cf53e3d7cf27f6"
        }
      ]
    }
  ]
}
